services:
  chroma:
    image: chromadb/chroma:1.0.20
    # ports:
    #   - "8000:8000"
    volumes:
      - chromadb:/data
    environment:
      IS_PERSISTENT: true
      ANONYMIZED_TELEMETRY: false
  postgres:
    image: postgres:alpine3.22
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  llm-agent-2:
    build: .
    # develop:
      # watch:
        # - action: rebuild
        #   path: ./pyproject.toml
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # - .:/app
      # - /app/.venv
      - ./backends.yaml:/app/backends.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "5047:5047"
    env_file:
      - .env
volumes:
  chromadb:
  postgres_data:
